project_id = "drooxdzcemoibkplprdp"

[functions.mux-assets]
verify_jwt = false

[functions.process-square-payment]
verify_jwt = false

[functions.process-refund]
verify_jwt = false

[functions.finalize-purse]
verify_jwt = false